filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/kirilltitov/go-musthave-diploma/internal/storage:
    interfaces:
      Storage:
  github.com/kirilltitov/go-musthave-diploma/internal/accrual:
    interfaces:
      Accrual:
